name: PHPStan Static Analyzer
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  run-phpstan:
    name: Run PHPStan
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: json, xdebug
        tools: composer:v2

    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: composer install --prefer-dist

    - name: Run PHPStan
      continue-on-error: true
      run: vendor/bin/phpstan analyze --error-format=sarif > phpstan-results.sarif

    - name: Show PHPStan Results
      continue-on-error: true
      run: cat phpstan-results.sarif

    - name: Upload analysis results to GitHub
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: phpstan-results.sarif
        wait-for-processing: true
